"""Cookie (de)serialization for the auth service — no heavy dependencies.

The extractor reads cookies with ``curl -b <file>``, which expects the **Netscape
HTTP Cookie File** format (tab-separated, 7 columns). These helpers turn either
Playwright cookie dicts or a raw ``Cookie:`` header string into that format, so both
the browser-capture flow and the manual paste fallback land in the same file.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

_NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by carrefour_receipts_api.auth_service — do not edit by hand.\n"
)

# Cookies pasted via a raw header have no domain; default them to Carrefour.
DEFAULT_DOMAIN = ".carrefour.fr"


def _netscape_line(
    *, domain: str, path: str, secure: bool, expires: int, name: str, value: str
) -> str:
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    secure_flag = "TRUE" if secure else "FALSE"
    return "\t".join(
        [
            domain,
            include_subdomains,
            path or "/",
            secure_flag,
            str(int(expires)),
            name,
            value,
        ]
    )


def playwright_cookies_to_netscape(cookies: list[dict[str, Any]]) -> str:
    """Render Playwright ``context.cookies()`` output as a Netscape cookie file."""
    lines = [_NETSCAPE_HEADER]
    for c in cookies:
        expires = c.get("expires", 0)
        # Playwright uses -1 for session cookies; Netscape uses 0.
        expires = 0 if expires is None or expires < 0 else int(expires)
        lines.append(
            _netscape_line(
                domain=c.get("domain", DEFAULT_DOMAIN),
                path=c.get("path", "/"),
                secure=bool(c.get("secure", False)),
                expires=expires,
                name=c["name"],
                value=c.get("value", ""),
            )
        )
    return "\n".join(lines) + "\n"


def cookie_header_to_netscape(header: str, domain: str = DEFAULT_DOMAIN) -> str:
    """Convert a raw ``name=value; name2=value2`` Cookie header to Netscape format.

    This is the manual fallback: copy the ``cookie:`` header (or the ``-b`` value of
    a *Copy as cURL*) from the browser devtools and paste it. All cookies are written
    under ``domain`` as secure session cookies.
    """
    header = header.strip()
    if header.lower().startswith("cookie:"):
        header = header[len("cookie:") :].strip()

    lines = [_NETSCAPE_HEADER]
    count = 0
    for pair in header.split(";"):
        pair = pair.strip()
        if not pair or "=" not in pair:
            continue
        name, value = pair.split("=", 1)
        name, value = name.strip(), value.strip()
        if not name:
            continue
        lines.append(
            _netscape_line(domain=domain, path="/", secure=True, expires=0, name=name, value=value)
        )
        count += 1
    if count == 0:
        raise ValueError("No valid 'name=value' cookies found in the pasted header.")
    return "\n".join(lines) + "\n"


def write_cookies_file(netscape_text: str, cookies_file: str | Path) -> int:
    """Write a Netscape cookie file (creating parent dirs) and return the cookie count."""
    path = Path(cookies_file)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(netscape_text, encoding="utf-8")
    return count_cookies(netscape_text)


def count_cookies(netscape_text: str) -> int:
    """Count cookie rows (non-comment, non-blank lines) in Netscape text."""
    return sum(
        1 for line in netscape_text.splitlines() if line.strip() and not line.startswith("#")
    )
